# Generated by Django 2.1.5 on 2019-03-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0012_auto_20190302_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buyer_demand',
        ),
    ]
