# Generated by Django 2.1.5 on 2019-03-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0013_delete_buyer_demand'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer_demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=90)),
                ('crop_name', models.CharField(max_length=90)),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('bought', models.CharField(max_length=90)),
                ('flag', models.IntegerField(default=0)),
                ('deadline', models.CharField(max_length=10)),
            ],
        ),
    ]
